# pyproject.toml
[project]
name = "cbioportal_export"
version = "0.1.0"
requires-python = ">=3.9,<3.12"
dependencies = [
  "synapseclient[pandas]>=4,<5",
  "pandas>=2.2",
  "pyyaml=6.0"
]

[dependency-groups]
dev = ["pytest"]